Kotaro editpage
watnows/hackathon-2023-TeamA pull request #49
Opened 2023-10-09 15:04 UTC by kotarowakuwaku

2023-10-14 15:52 UTC, YukaChoco requested changes
`createColor.tsx`のコードを、同じフォルダにある`mycard.tsx`にコピペしてほしいです！

あと、使われていない`import`や変数、コメントアウトの部分は削除お願いします！
(ハッカソン中はどうでもよかった(こら)けど、きれいなコードにしていきたい！)

他にも時間あるときにやってほしいこと(いずれやる)
- 編集完了画面を`mode='完了'`として表示(`editOk.tsx`にある程度でき上がってる)
- 完了画面で保存して終了を押したらデータをまとめてmakeCardsに入れてDBに追加
- cards(他人のカードを作る画面)の作成

2023-10-14 15:52 UTC, YukaChoco commented on src/pages/make/createColor.tsx
> +  const [mode, setMode] = useState('入力');
useStateを使った変数は一番上にまとめて定義お願いします！

2023-10-14 15:52 UTC, YukaChoco commented on src/pages/make/createColor.tsx
> +                        </div>
ここは`InputColors.tsx`というコンポーネントに切り分けてみて下さい！
`handle`とか`color`とかを引数にするとよいかと思います！

2023-10-14 15:52 UTC, YukaChoco commented on src/pages/make/createColor.tsx
> +                        </div>
ここも`InputTexts.tsx`で！

2023-10-14 15:52 UTC, YukaChoco commented on src/pages/make/createColor.tsx
> +                    if (mode=="デザイン") {
FYI `if`で`return`してもいいし、三項演算子も結構きれいに書けますよ～

2023-10-14 15:52 UTC, YukaChoco commented on src/pages/make/createColor.tsx
> +  const [mode, setMode] = useState('入力');
型はstringか`'入力'|'デザイン'|'完了'`でお願いします！

2023-10-14 15:52 UTC, YukaChoco commented on src/pages/make/createColor.tsx
> +                          <SecondaryBtn text="編集完了" onClick={() => console.log('Secondarybtn Clicked')} />
ボタンなしでいこうかなと思うので、削除お願いします！

2023-11-04 19:37 UTC, YukaChoco commented
### 実装した主な内容
- developのマージと最新状態に沿って修正
- 他人の名刺作成画面の実装(入力から登録完了まで)

2023-11-04 19:37 UTC, YukaChoco requested changes
### 今後お願いしたいこと
- 前回やったコードがなくなってそうなので`makeMyCard`までもっかい頑張ってもらいたい！
- 前回のレビューも含めて、コメントした部分の修正
- コンポーネント名が`TextInput`・`InputTexts`などだと分かりずらいのでどちらかor両方修正を加えたい
- 基本的には`make/cards.tsx`に参考にできるコードがあるかも

2023-11-04 19:37 UTC, YukaChoco commented on src/conponents/InputColors.tsx
> +        <div className={styles.space} />
`EditComplete.tsx`を参考にしてspaceなどを調整してみてください。おそらくCSSModulesを使わずに書けそうです！

2023-11-04 19:37 UTC, YukaChoco commented on src/conponents/InputColors.tsx
> +        <div className={styles.space} />
MUIのsxでもスタイルが指定できるため、余白を取るだけならCSSModulesファイルを増やして指定する必要性がない気がしました！
今回くらいのシンプルなスタイルだと直接書いちゃった方がおそらく可読性も上がる。。

2023-11-04 19:37 UTC, YukaChoco commented on src/conponents/InputTexts.tsx
> +  handleOrganization:(event: React.ChangeEvent<HTMLInputElement>) => void;
ここは要相談だなって思ってます。
propsが多すぎてごちゃごちゃしてしまっている。

2023-11-04 19:37 UTC, YukaChoco commented on src/conponents/InputTexts.tsx
> +      <div className={styles.space} />
勝手に順序入れ替えました。

2023-11-04 19:37 UTC, YukaChoco commented on src/pages/make/mycard.tsx
> +  }
userIdがnullだった場合、
- ログインしてください
- ログイン画面への遷移ボタン(router.push('/?nextPage=${router.asPath}'))
のみ出力してください

参考：https://github.com/watnows/hackathon-2023-TeamA/pull/63#pullrequestreview-1713715017

2023-11-04 19:37 UTC, YukaChoco commented on src/pages/make/mycard.tsx
> +                {...mode === "完了" ? null : { onClick_edit: () => setMode("完了") }}
...を使うよりは、onClick_edit={`この中で工夫すると綺麗！`}

2023-11-06 07:39 UTC, shimochan commented
よくがんばりました

2023-11-11 14:21 UTC, YukaChoco commented
わああああ
待ってごめん、sxに変更するやつやってしもた(#82 )
コミットの粒度が細かくなってるの感動した🥲
レビュー慌ててします

コミット名での判断になっちゃうんだけど、今回作ってもらった入力フォームとかをまとめているコンポーネントの名前が確かややこしかったからそこだけ修正してほしい！！

2023-11-13 07:55 UTC, YukaChoco commented
### お願いしたいこと
- InputTextなどのtextをlabelTextに変更
- EditTextsの型PropsをEditTextsPropsに変更
- SwitchButtonのコメントアウトされているmergin削除
- DisplayCardの必要ないPropsを削除

2023-11-13 09:30 UTC, YukaChoco approved these changes
LGTMMMMMM

2023-11-13 09:31 UTC, merged