名刺詳細画面で登録機能や閲覧できるかの分岐を実装
watnows/hackathon-2023-TeamA pull request #64
Opened 2023-11-04 05:34 UTC by YukaChoco

issue
#62

2023-11-04 15:13 UTC, mercy34mercy requested changes
いろいろ書いてますが、動けばいい！という考え方もあるのでそんなに重く受け止めないでください。
ただ、コードは他の人が見るわけで、その人はこのコードを書いた人の気持ちがわかるエスパーじゃないのでせめて、コードにはできるだけコンテキスト(このコードの意味とか)を込めるようにしましょう。
個人開発でも多分半年もしたら自分の書いたコードのことなんて忘れると思うので重要なスキルです。
firebaseの関数にはどんなことするのか、`userIDから持っている名刺を取得する`とか書いてもいいと思います。

2023-11-04 15:13 UTC, mercy34mercy commented on src/utils/ok/getMyCardIds.tsx
>  interface GetData {
データの型の名前にGetは不適切かな
なんのデータかわからないので、UserDataとかかな。

2023-11-04 15:13 UTC, mercy34mercy commented on src/utils/ok/getHaveCardIds.tsx
>  interface GetData {
ここの型の名前も治してね。

2023-11-04 15:13 UTC, mercy34mercy commented on src/utils/ok/getMyCardIds.tsx
>  export default async function getMyCardIds(userid: string) {
getMyCardIdsは結構いいな名前だと思うけど、getMyCardIDsByUserIDとかだとベストかな。
個人的には、IdよりID派です。⇦これは流派だからどっちでもいいと思います。

2023-11-04 15:13 UTC, mercy34mercy commented on src/utils/ok/getHaveCardIds.tsx
>  export default async function getHaveCardIds(userId: string) {
ここも、getHaveCardIDsByUserIDかな。Byがあると、何で検索してるのか特に関数呼び出す時わかりやすくていいです。

2023-11-04 15:13 UTC, mercy34mercy commented on src/utils/ok/getHaveCardIds.tsx
>    const querySnapshot = await getDoc(doc(db, 'users', userId))
querySnapshotは多分ドキュメントそのままだから、なんのデータなのかを変数名に入れよう

2023-11-04 15:13 UTC, mercy34mercy commented on src/pages/index.tsx
>                  await firebaseLogin()
調べずに書いてます。fireabselogin()で新規登録もログインもできるんだっけ？

2023-11-04 19:13 UTC, YukaChoco commented on src/pages/edit/mycard.tsx
> +}
「他人の名刺の編集」と「ユーザ自身の名刺の編集」があって、画面が少し異なるのでファイルを分けて、一旦作成中ということにしました。

2023-11-04 19:13 UTC, YukaChoco commented on src/pages/index.tsx
>                  await firebaseLogin()
一旦どちらでも行けるような状態になってます！
今後修正必要だなって感じです！

2023-11-04 19:17 UTC, YukaChoco commented
### 追加で聞きたいこと
- 列挙型の適切な使い方がわかりません(もう一度調べます)
- loadingの保持の仕方(様々なLoadingがあり、一括で管理したい気がします。)
- if elseのフォーマットが他と違うという部分が分かりませんでした
- getURLの不適切な点が分かりませんでした(補完とは)

2023-11-05 02:39 UTC, mercy34mercy commented
今夜コメント返します。

2023-11-05 14:08 UTC, mercy34mercy commented on src/pages/index.tsx
>                  await firebaseLogin()
了解ですLGTM

2023-11-05 14:16 UTC, mercy34mercy reviewed
だいぶ治ってていいと思います。
この感じでコードを書く時気を使えるようになるとbetterです。

2023-11-05 14:16 UTC, mercy34mercy commented on src/pages/edit/mycard.tsx
> +}
了解ですLGTM

2023-11-05 14:16 UTC, mercy34mercy commented on src/styles/globals.css
> +  background-color: #F4F5FC;
これは対応しなくていいと思う

2023-11-05 14:16 UTC, mercy34mercy commented on src/pages/card/[cardid].tsx
> +      return (<SecondaryButton text='この名刺を編集する' onClick={() => router.push(`/edit/${cardType === CardType.My ? 'mycard' : 'card'}?cardId=${cardId}`)} />);
mycard cardをenumにするか、、、。
できればくらいかな。他で使いそうなことが予想されればした方がいいと思います

2023-11-05 14:42 UTC, mercy34mercy commented
@YukaChoco 
回答です

> 列挙型の適切な使い方がわかりません(もう一度調べます)


あってるよ、確かにコード的には何が変わってんて感じかもしれんけど、'have'のような文字列複数回をベタ打ちするのはあまりよしとされてないので、今回の場合状態を表す文字列が複数あるのでenumでまとめて文字列を定義してね！って感じです。

> loadingの保持の仕方(様々なLoadingがあり、一括で管理したい気がします。)


それは思った。どっちかというとアルゴリズム的な部分が強い気がするから頑張ってみて、別にglobalstateとかは使う必要がないと思うので頑張ればいい感じに管理できるはず。

> if elseのフォーマットが他と違うという部分が分かりませんでした
```typescript
      if (result) {
        setCardType('have');
      }
      else {
        console.error('登録に失敗しました');
      }
```
上を下にこう変えれば大丈夫です。
```typescript
      if (result) {
        setCardType('have');
      } else {
        console.error('登録に失敗しました');
      }
```
> getURLの不適切な点が分かりませんでした(補完とは)


toURL('instagram',userId)という関数を入力するときに、VSCodeとかintelliJIDEとかなんでも、toUくらいで補完が出てきて最後まで入力する必要がないと思います。しかし、'instagram'という文字列は、copolitがワンチャン出してくらいで、IDEの補完で入力できず面倒だということです。解決策の一つが、enumを使って、snsType.Instagram か snsType.Xとすることで、補完が効くようにはなります。 toInstagramProfileURLとかならtoInsぐらいで多分補完で入力を終えることができるはず。

`根本的な問題`
そもそも、toURL関数に、toURL('instagram', card.X)のような感じで、instagramのURLが欲しいのに間違えて引数にXを入れちゃうみたいなことをこの関数は防げないです。無理にまとめようとした結果関数がバグを引き起こしやすくなってしまっている。


`推奨されるコード`
typescriptを使うならこれくらい型で守られた関数を作ってあげてほしい。(主がGo使いなので過剰になりすぎてる可能性はある)

```ts
type XUserIdType = string;
type InstagramUserIdType = string;


export interface CardData {
  id: string;
  authorId: string;
  name: string;
  organization: string;
  xUserId: XUserIdType;
  instagramUserId:instagramUserIdType;
  textColor: string;
  bgColor: string;
  protected: boolean;
}

function toInstagramProfileURL(instagram: InstagramUserIdType): string {
    return `https://www.instagram.com/${instagram}/`;
}

function toXProfileURL(x: XUserIdType): string {
    return `https://x.com/${x}`;
}
```

2023-11-06 10:00 UTC, YukaChoco commented
@mercy34mercy 
ありがとうございます！！！

XUserIdTypeをtypeとして外で定義していると思うのですが、stringだけでも型として用意して関数で使う方がbetterなんでしょうか。
stringくらいならそのままでいいのではと思ってしまいました。理由があればぜひ教えてください！

2023-11-06 15:45 UTC, mercy34mercy commented
あと、このPRでファイル構造とか、Loadingの管理とかを頑張るとPRがでかくなって何を変更したPRなのかよくわからなくなってしまうので、`名刺詳細画面で登録機能や閲覧できるかの分岐を実装`というところに集中していいともいます。

2023-11-06 16:34 UTC, mercy34mercy approved these changes
動作上はLGTM ⭐

2023-11-09 06:59 UTC, YukaChoco commented on src/utils/ok/getHaveCardIds.tsx
>    const fetchIds: GetData = querySnapshot.data() as GetData
ユーザーデータに現状Idしか無かったためこう書きました。
今後増える可能性等を考えると良くないですが、、、修正しました。

2023-11-09 07:03 UTC, YukaChoco commented on src/styles/globals.css
> +  background-color: #F4F5FC;
> featureだからやらなくていいよ

について詳しく教えてください

2023-11-09 07:06 UTC, YukaChoco commented on src/utils/ok/getMyCardIds.tsx
>  export default async function getMyCardIds(userid: string) {
回収が厳しそうなのでこのプロジェクトではIdsでいくようにします。
IDのが綺麗ですね。私もこっち派らしいです。

2023-11-09 07:21 UTC, YukaChoco commented on src/pages/card/[cardid].tsx
> +      return (<SecondaryButton text='この名刺を編集する' onClick={() => router.push(`/edit/${cardType === CardType.My ? 'mycard' : 'card'}?cardId=${cardId}`)} />);
使われそうな気がするのでそうしておきます

2023-11-09 08:29 UTC, mercy34mercy commented on src/styles/globals.css
> +  background-color: #F4F5FC;
featureは未来にやればいいみたいな感じかな・

2023-11-09 08:45 UTC, merged

2023-11-09 08:47 UTC, YukaChoco commented
@mercy34mercy 早急なレビュー(？)ありがとうございます！！
もしまだ(または今後)言いたいことあったらばんばん書いてもらって大丈夫です😇
直すのをissueに増やします！